# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven
env:
  ALLURE_VERSION: "2.10.0"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    name: Tests on JDK
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        java: [ 8, 11, 17 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk

      - name: Build with Maven
        id: build
        run: mvn install -DskipTests -ntp

      - name: Get Allure history
        uses: actions/checkout@v3
        id: allure-setup
        if: steps.build.outcome == 'success'
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Tests
        id: functests
        timeout-minutes: 15
        run: mvn test -Pci -ntp

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Upload Allure report
        uses: actions/upload-artifact@master
        if: github.event_name == 'pull_request' && failure()
        with:
          name: Allure report
          path: ./target/site

      - name: Deploy Allure report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Check tests are passed
        if: ${{ steps.functests.outcome != 'success' }}
        run: |
          echo Tests result: ${{ steps.functests.outcome }}
          exit 1